### ISSUE TITLE
Possible Bug when assigning positions

### ISSUE THREAD

**Issue by bestform** [JamesMilnerUK/quadtree-go#2]
Hey,

I just read the code out of curiosity and stumbled upon this line: https://github.com/JamesMilnerUK/quadtree-go/blob/91949e97f7b872f8e5df8824e977989399355b9f/quadtree.go#L29

This sounds odd to me. Is there a reason you assign X to the Y value?

**Comment by JamesMilnerUK** [comment]
Good spot, definitely not intentional. Should be fixed now; I'm going to add some more unit tests when I have a moment.
